remote_theme: "mmistakes/minimal-mistake@4.24.0"
title: Timothy Lu's Portfolio
description: Work in Progress on my Data Science Portfolio!
github:
  is_project_page: false
plugins: jekyll-include-cache
